services:
    dsr.sceditor.event.sce:
        class: dsr\sceditor\event\listener
        arguments:
            - '@dbal.conn'
            - '@template'
            - '@config'
            - '@user'
            - '%core.root_path%'
        tags:
            - { name: event.listener }